<?php

echo "hello\n"; // Line 1
echo "hello\n"; // Line 2
echo "hello\n"; // Line 3
echo "hello\n"; // Line 4
echo "hello\n"; // Line 5
echo "hello\n"; // Line 6
echo "hello\n"; // Line 7
echo "hello\n"; // Line 8
echo "hello\n"; // Line 9
echo "hello\n"; // Line 10
echo "hello\n"; // Line 11
echo "hello\n"; // Line 12
echo "hello\n"; // Line 13
echo "hello\n"; // Line 14
echo "hello\n"; // Line 15
echo "hello\n"; // Line 16
echo "hello\n"; // Line 17
echo "hello\n"; // Line 18
echo "hello\n"; // Line 19
echo "hello\n"; // Line 20
echo "hello\n"; // Line 21
echo "hello\n"; // Line 22
echo "hello\n"; // Line 23
echo "hello\n"; // Line 24
echo "hello\n"; // Line 25
echo "hello\n"; // Line 26
echo "hello\n"; // Line 27
echo "hello\n"; // Line 28
echo "hello\n"; // Line 29
echo "hello\n"; // Line 30
echo "hello\n"; // Line 31
echo "hello\n"; // Line 32
echo "hello\n"; // Line 33
echo "hello\n"; // Line 34
echo "hello\n"; // Line 35
echo "hello\n"; // Line 36
echo "hello\n"; // Line 37
echo "hello\n"; // Line 38
echo "hello\n"; // Line 39
echo "hello\n"; // Line 40
echo "hello\n"; // Line 41
echo "hello\n"; // Line 42
echo "hello\n"; // Line 43
echo "hello\n"; // Line 44
echo "hello\n"; // Line 45
echo "hello\n"; // Line 46
echo "hello\n"; // Line 47
echo "hello\n"; // Line 48
echo "hello\n"; // Line 49
echo "hello\n"; // Line 50
echo "hello\n"; // Line 51
echo "hello\n"; // Line 52
echo "hello\n"; // Line 53
echo "hello\n"; // Line 54
echo "hello\n"; // Line 55
echo "hello\n"; // Line 56
echo "hello\n"; // Line 57
echo "hello\n"; // Line 58
echo "hello\n"; // Line 59
echo "hello\n"; // Line 60
echo "hello\n"; // Line 61
echo "hello\n"; // Line 62
echo "hello\n"; // Line 63
echo "hello\n"; // Line 64
echo "hello\n"; // Line 65
echo "hello\n"; // Line 66
echo "hello\n"; // Line 67
echo "hello\n"; // Line 68
echo "hello\n"; // Line 69
echo "hello\n"; // Line 70
echo "hello\n"; // Line 71
echo "hello\n"; // Line 72
echo "hello\n"; // Line 73
echo "hello\n"; // Line 74
echo "hello\n"; // Line 75
echo "hello\n"; // Line 76
echo "hello\n"; // Line 77
echo "hello\n"; // Line 78
echo "hello\n"; // Line 79
echo "hello\n"; // Line 80
echo "hello\n"; // Line 81
echo "hello\n"; // Line 82
echo "hello\n"; // Line 83
echo "hello\n"; // Line 84
echo "hello\n"; // Line 85
echo "hello\n"; // Line 86
echo "hello\n"; // Line 87
echo "hello\n"; // Line 88
echo "hello\n"; // Line 89
echo "hello\n"; // Line 90
echo "hello\n"; // Line 91
echo "hello\n"; // Line 92
echo "hello\n"; // Line 93
echo "hello\n"; // Line 94
echo "hello\n"; // Line 95
echo "hello\n"; // Line 96
echo "hello\n"; // Line 97
echo "hello\n"; // Line 98
echo "hello\n"; // Line 99
echo "hello\n"; // Line 100
echo "hello\n"; // Line 1
echo "hello\n"; // Line 2
echo "hello\n"; // Line 3
echo "hello\n"; // Line 4
echo "hello\n"; // Line 5
echo "hello\n"; // Line 6
echo "hello\n"; // Line 7
echo "hello\n"; // Line 8
echo "hello\n"; // Line 9
echo "hello\n"; // Line 10
echo "hello\n"; // Line 11
echo "hello\n"; // Line 12
echo "hello\n"; // Line 13
echo "hello\n"; // Line 14
echo "hello\n"; // Line 15
echo "hello\n"; // Line 16
echo "hello\n"; // Line 17
echo "hello\n"; // Line 18
echo "hello\n"; // Line 19
echo "hello\n"; // Line 20
echo "hello\n"; // Line 21
echo "hello\n"; // Line 22
echo "hello\n"; // Line 23
echo "hello\n"; // Line 24
echo "hello\n"; // Line 25
echo "hello\n"; // Line 26
echo "hello\n"; // Line 27
echo "hello\n"; // Line 28
echo "hello\n"; // Line 29
echo "hello\n"; // Line 30
echo "hello\n"; // Line 31
echo "hello\n"; // Line 32
echo "hello\n"; // Line 33
echo "hello\n"; // Line 34
echo "hello\n"; // Line 35
echo "hello\n"; // Line 36
echo "hello\n"; // Line 37
echo "hello\n"; // Line 38
echo "hello\n"; // Line 39
echo "hello\n"; // Line 40
echo "hello\n"; // Line 41
echo "hello\n"; // Line 42
echo "hello\n"; // Line 43
echo "hello\n"; // Line 44
echo "hello\n"; // Line 45
echo "hello\n"; // Line 46
echo "hello\n"; // Line 47
echo "hello\n"; // Line 48
echo "hello\n"; // Line 49
echo "hello\n"; // Line 50
echo "hello\n"; // Line 51
echo "hello\n"; // Line 52
echo "hello\n"; // Line 53
echo "hello\n"; // Line 54
echo "hello\n"; // Line 55
echo "hello\n"; // Line 56
echo "hello\n"; // Line 57
echo "hello\n"; // Line 58
echo "hello\n"; // Line 59
echo "hello\n"; // Line 60
echo "hello\n"; // Line 61
echo "hello\n"; // Line 62
echo "hello\n"; // Line 63
echo "hello\n"; // Line 64
echo "hello\n"; // Line 65
echo "hello\n"; // Line 66
echo "hello\n"; // Line 67
echo "hello\n"; // Line 68
echo "hello\n"; // Line 69
echo "hello\n"; // Line 70
echo "hello\n"; // Line 71
echo "hello\n"; // Line 72
echo "hello\n"; // Line 73
echo "hello\n"; // Line 74
echo "hello\n"; // Line 75
echo "hello\n"; // Line 76
echo "hello\n"; // Line 77
echo "hello\n"; // Line 78
echo "hello\n"; // Line 79
echo "hello\n"; // Line 80
echo "hello\n"; // Line 81
echo "hello\n"; // Line 82
echo "hello\n"; // Line 83
echo "hello\n"; // Line 84
echo "hello\n"; // Line 85
echo "hello\n"; // Line 86
echo "hello\n"; // Line 87
echo "hello\n"; // Line 88
echo "hello\n"; // Line 89
echo "hello\n"; // Line 90
echo "hello\n"; // Line 91
echo "hello\n"; // Line 92
echo "hello\n"; // Line 93
echo "hello\n"; // Line 94
echo "hello\n"; // Line 95
echo "hello\n"; // Line 96
echo "hello\n"; // Line 97
echo "hello\n"; // Line 98
echo "hello\n"; // Line 99
echo "hello\n"; // Line 100
echo "hello\n"; // Line 1
echo "hello\n"; // Line 2
echo "hello\n"; // Line 3
echo "hello\n"; // Line 4
echo "hello\n"; // Line 5
echo "hello\n"; // Line 6
echo "hello\n"; // Line 7
echo "hello\n"; // Line 8
echo "hello\n"; // Line 9
echo "hello\n"; // Line 10
echo "hello\n"; // Line 11
echo "hello\n"; // Line 12
echo "hello\n"; // Line 13
echo "hello\n"; // Line 14
echo "hello\n"; // Line 15
echo "hello\n"; // Line 16
echo "hello\n"; // Line 17
echo "hello\n"; // Line 18
echo "hello\n"; // Line 19
echo "hello\n"; // Line 20
echo "hello\n"; // Line 21
echo "hello\n"; // Line 22
echo "hello\n"; // Line 23
echo "hello\n"; // Line 24
echo "hello\n"; // Line 25
echo "hello\n"; // Line 26
echo "hello\n"; // Line 27
echo "hello\n"; // Line 28
echo "hello\n"; // Line 29
echo "hello\n"; // Line 30
echo "hello\n"; // Line 31
echo "hello\n"; // Line 32
echo "hello\n"; // Line 33
echo "hello\n"; // Line 34
echo "hello\n"; // Line 35
echo "hello\n"; // Line 36
echo "hello\n"; // Line 37
echo "hello\n"; // Line 38
echo "hello\n"; // Line 39
echo "hello\n"; // Line 40
echo "hello\n"; // Line 41
echo "hello\n"; // Line 42
echo "hello\n"; // Line 43
echo "hello\n"; // Line 44
echo "hello\n"; // Line 45
echo "hello\n"; // Line 46
echo "hello\n"; // Line 47
echo "hello\n"; // Line 48
echo "hello\n"; // Line 49
echo "hello\n"; // Line 50
echo "hello\n"; // Line 51
echo "hello\n"; // Line 52
echo "hello\n"; // Line 53
echo "hello\n"; // Line 54
echo "hello\n"; // Line 55
echo "hello\n"; // Line 56
echo "hello\n"; // Line 57
echo "hello\n"; // Line 58
echo "hello\n"; // Line 59
echo "hello\n"; // Line 60
echo "hello\n"; // Line 61
echo "hello\n"; // Line 62
echo "hello\n"; // Line 63
echo "hello\n"; // Line 64
echo "hello\n"; // Line 65
echo "hello\n"; // Line 66
echo "hello\n"; // Line 67
echo "hello\n"; // Line 68
echo "hello\n"; // Line 69
echo "hello\n"; // Line 70
echo "hello\n"; // Line 71
echo "hello\n"; // Line 72
echo "hello\n"; // Line 73
echo "hello\n"; // Line 74
echo "hello\n"; // Line 75
echo "hello\n"; // Line 76
echo "hello\n"; // Line 77
echo "hello\n"; // Line 78
echo "hello\n"; // Line 79
echo "hello\n"; // Line 80
echo "hello\n"; // Line 81
echo "hello\n"; // Line 82
echo "hello\n"; // Line 83
echo "hello\n"; // Line 84
echo "hello\n"; // Line 85
echo "hello\n"; // Line 86
echo "hello\n"; // Line 87
echo "hello\n"; // Line 88
echo "hello\n"; // Line 89
echo "hello\n"; // Line 90
echo "hello\n"; // Line 91
echo "hello\n"; // Line 92
echo "hello\n"; // Line 93
echo "hello\n"; // Line 94
echo "hello\n"; // Line 95
echo "hello\n"; // Line 96
echo "hello\n"; // Line 97
echo "hello\n"; // Line 98
echo "hello\n"; // Line 99
echo "hello\n"; // Line 100

?>